name: Build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: oracle
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    -
      name: Build
      run: |
        ./mvnw -B package --file pom.xml
